const $=s=>document.querySelector(s); const app=$('#app'); let state={user:null,page:'dashboard',data:{}};
const fmt=n=>new Intl.NumberFormat('ar-SA',{style:'currency',currency:'SAR'}).format(Number(n||0));
async function api(path,opt={}){opt.headers={...(opt.headers||{}),'Content-Type':'application/json','x-user':state.user?.username||localStorage.user||''}; if(opt.body&&typeof opt.body!=='string')opt.body=JSON.stringify(opt.body); const r=await fetch(path,opt); const d=await r.json().catch(()=>({})); if(!r.ok) throw new Error(d.error||'خطأ'); return d;}
async function loginView(){
  app.innerHTML=`<div class="login"><div class="box"><h1>AMS ERP ULTRA USERS</h1><p>اختيار المستخدم + تغيير كلمة المرور + إدارة الصلاحيات</p><select id="u"><option value="admin">admin - Admin</option><option value="accountant">accountant - Accountant</option><option value="viewer">viewer - Viewer</option></select><br><br><input id="p" value="1234" type="password" placeholder="كلمة المرور"><br><br><button class="primary" onclick="login()">دخول</button><p>اختر المستخدم من القائمة ثم أدخل كلمة المرور</p></div></div>`;
  try{let users=await fetch('/api/users-public').then(r=>r.json()); let sel=$('#u'); if(sel&&Array.isArray(users)){sel.innerHTML=users.map(u=>`<option value="${u.username}">${u.username} - ${u.role}</option>`).join('');}}
  catch(e){}
}
async function login(){try{let d=await api('/api/login',{method:'POST',body:{username:$('#u').value,password:$('#p').value}});state.user={username:d.username,role:d.role,permissions:d.permissions};localStorage.user=d.username; render();}catch(e){alert(e.message)}}
function shell(){let pages=[['dashboard','لوحة التحكم'],['suppliers','الموردون'],['purchases','المشتريات'],['returns','المرتجعات والخصومات'],['payments','المدفوعات'],['statement','كشف حساب مورد'],['balances','تقرير أرصدة الموردين'],['journals','القيود اليومية'],['vat','تقرير VAT'],['workflow','اعتماد المستندات'],['attachments','المرفقات'],['locks','الإقفال الشهري'],['audit','Audit Log'],['backup','نسخ و Excel'],['users','المستخدمون والصلاحيات'],['settings','إعدادات القيود والصلاحيات']];return `<div class="layout"><aside class="side"><div class="brand">AMS ERP FINAL<br><small>${state.user.username} - ${state.user.role}</small></div><div class="nav">${pages.map(p=>`<button class="${state.page==p[0]?'active':''}" onclick="go('${p[0]}')">${p[1]}</button>`).join('')}<button onclick="logout()">خروج</button></div></aside><main class="main"><div class="top"><b>${pages.find(p=>p[0]==state.page)?.[1]}</b><div><input style="width:280px" id="smart" oninput="smartSearch(this.value)" placeholder="بحث ذكي باسم المورد أو رقم الفاتورة"></div></div><div class="notice" id="notice">النظام جاهز — الصلاحية: ${state.user.role}</div><div class="content" id="view"></div></main></div>`}
function logout(){localStorage.removeItem('user');state.user=null;loginView()} async function go(p){state.page=p; await render()}
async function render(){if(!localStorage.user&&!state.user)return loginView(); if(!state.user){state.user={username:localStorage.user,role:'',permissions:{}}} app.innerHTML=shell(); await load(); draw();}
async function load(){state.data=await api('/api/data')}
function draw(){({dashboard,suppliers,purchases,returns,payments,statement,balances,journals,vat,workflow,attachments,locks,audit,backup,users,settings}[state.page]||dashboard)()}
function can(p){return !!state.user.permissions?.[p]}
function badge(s){let c=s==='معتمد'||s==='مرحل'?'approved':s==='ملغي'?'cancelled':'draft';return `<span class="status ${c}">${s||'مسودة'}</span>`}
function inputRow(fields,id){return `<div class="grid">${fields.map(f=> f.type==='select'?`<select id="${id}_${f.k}">${(f.opts||[]).map(o=>`<option>${o}</option>`).join('')}</select>`:`<input id="${id}_${f.k}" type="${f.type||'text'}" placeholder="${f.t}" value="${f.v||''}">`).join('')}</div>`}
function vals(id,keys){let o={}; keys.forEach(k=>{let e=$('#'+id+'_'+k); if(e)o[k]=e.value}); return o;}
function table(head,rows){return `<div class="tablewrap"><table><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${head.length}">لا توجد بيانات</td></tr>`}</tbody></table></div>`}
function actionBtns(tableName,r){let e=can('canEdit')?`<button class="muted" onclick='editRow("${tableName}",${JSON.stringify(r).replaceAll("'","&#39;")})'>تعديل</button>`:''; let d=can('canDelete')&&(!r.status||r.status==='مسودة')?`<button class="danger" onclick="delRow('${tableName}','${r.id}')">حذف</button>`:''; let a=can('canApprove')&&r.status==='مسودة'?`<button class="ok" onclick="wf('${tableName}','${r.id}','approve')">اعتماد</button>`:''; let p=can('canApprove')&&r.status!=='مرحل'&&r.status!=='ملغي'?`<button class="primary" onclick="wf('${tableName}','${r.id}','post')">ترحيل</button>`:''; let c=can('canCancel')&&r.status!=='ملغي'?`<button class="danger" onclick="cancelDoc('${tableName}','${r.id}')">إلغاء</button>`:''; let at=can('canAttach')?`<button class="muted" onclick="attachBox('${tableName}','${r.id}')">مرفق</button>`:''; return e+d+a+p+c+at}
async function add(tableName,prefix){try{let keys={suppliers:['name','phone','tax','opening','notes'],purchases:['date','supplier','invoiceNo','beforeTax','tax','notes'],returns:['date','supplier','returnType','invoiceNo','beforeTax','tax','notes'],payments:['date','supplier','amount','method','notes']}[tableName]; await api('/api/'+tableName,{method:'POST',body:vals(prefix,keys)}); await render()}catch(e){alert(e.message)}}
async function editRow(tableName,row){if(row.status&&row.status!=='مسودة'&&!can('canApprove')) return alert('المستند معتمد أو مرحل ولا يعدله إلا Admin'); let keys=Object.keys(row).filter(k=>!['id','docNo','total','createdBy','createdAt','updatedBy','updatedAt','approvedBy','approvedAt','postedBy','postedAt','cancelledBy','cancelledAt'].includes(k));let data={};for(let k of keys){let v=prompt(k,row[k]??''); if(v===null)return; data[k]=v;}try{await api('/api/'+tableName+'/'+row.id,{method:'PUT',body:data});await render()}catch(e){alert(e.message)}}
async function delRow(tableName,id){if(!confirm('تأكيد الحذف؟'))return;try{await api('/api/'+tableName+'/'+id,{method:'DELETE'});await render()}catch(e){alert(e.message)}}
async function wf(t,id,act){try{await api(`/api/workflow/${t}/${id}/${act}`,{method:'POST'}); await render()}catch(e){alert(e.message)}}
async function cancelDoc(t,id){let reason=prompt('سبب الإلغاء'); if(reason===null)return; try{await api(`/api/workflow/${t}/${id}/cancel`,{method:'POST',body:{reason}}); await render()}catch(e){alert(e.message)}}
async function dashboard(){let d=await api('/api/dashboard');$('#view').innerHTML=`<div class="cards">${[['عدد الموردين',d.suppliers],['أرصدة أول المدة',fmt(d.opening)],['المشتريات',fmt(d.purchases)],['المدفوعات',fmt(d.payments)],['الخصومات/المرتجعات',fmt(d.returns)],['إجمالي المديونية',fmt(d.supplierTotal)],['مسودات',d.drafts],['معتمد/مرحل',d.approved],['المرفقات',d.attachments],['Audit Log',d.audit]].map(x=>`<div class="card"><div class="metric">${x[0]}</div><div class="value">${x[1]}</div></div>`).join('')}</div><div class="card"><h3>نسخة ERP احترافية نهائية</h3><p>Workflow + VAT تلقائي + ربط قيود قابل للتعديل + صلاحيات تفصيلية + ترقيم مستندات احترافي حسب السنة والشهر.</p><button class="primary" onclick="createOpeningJournal()">إنشاء القيد الافتتاحي من أرصدة الموردين</button></div>`}
async function createOpeningJournal(){try{let force=confirm('هل تريد إعادة إنشاء القيد الافتتاحي؟ OK = إعادة، Cancel = إنشاء إذا غير موجود');let r=await api('/api/create-opening-journal'+(force?'?force=1':''),{method:'POST'});alert(r.message||'تم إنشاء القيد الافتتاحي بإجمالي '+fmt(r.total)); await render()}catch(e){alert(e.message)}}
function suppliers(){let rows=state.data.suppliers.map(s=>`<tr><td>${s.name}</td><td>${s.phone||''}</td><td>${s.tax||''}</td><td>${fmt(s.opening)}</td><td>${s.notes||''}</td><td>${actionBtns('suppliers',s)}</td></tr>`);$('#view').innerHTML=`<div class="toolbar"><button class="ok" onclick="excel('suppliers')">Excel</button></div><div class="card"><h3>إضافة مورد</h3>${inputRow([{k:'name',t:'اسم المورد'},{k:'phone',t:'الجوال'},{k:'tax',t:'الرقم الضريبي'},{k:'opening',t:'رصيد أول المدة',type:'number'},{k:'notes',t:'ملاحظات'}],'sup')}<br><button class="primary" onclick="add('suppliers','sup')">حفظ</button></div>${table(['المورد','الجوال','الضريبي','رصيد أول المدة','ملاحظات','إجراءات'],rows)}`}
function vatRate(){return Number(state.data.settings?.vatRate||15)}
function autoTax(prefix){let before=Number($('#'+prefix+'_beforeTax')?.value||0); let tax=(before*vatRate()/100).toFixed(2); if($('#'+prefix+'_tax')) $('#'+prefix+'_tax').value=tax;}
function purchases(){let sup=state.data.suppliers.map(s=>s.name);let rows=state.data.purchases.map(r=>`<tr><td>${r.date}</td><td>${r.docNo||''}</td><td>${r.invoiceNo||''}</td><td>${r.supplier}</td><td>${fmt(r.beforeTax)}</td><td>${fmt(r.tax)}</td><td>${fmt(r.total)}</td><td>${badge(r.status)}</td><td>${actionBtns('purchases',r)}</td></tr>`);$('#view').innerHTML=`<div class="toolbar"><button class="ok" onclick="excel('purchases')">Excel</button></div><div class="card"><h3>فاتورة شراء</h3><p class="hint">يتم احتساب VAT تلقائيًا حسب الإعدادات، ويمكن تعديل الضريبة يدويًا عند الحاجة.</p>${inputRow([{k:'date',t:'التاريخ',type:'date'},{k:'supplier',type:'select',opts:sup},{k:'invoiceNo',t:'رقم فاتورة المورد'},{k:'beforeTax',t:'قبل الضريبة',type:'number'},{k:'tax',t:'VAT',type:'number'},{k:'notes',t:'ملاحظات'}],'pur')}<br><button class="muted" onclick="autoTax('pur')">حساب VAT</button><button class="primary" onclick="add('purchases','pur')">حفظ كمسودة</button></div>${table(['التاريخ','رقم النظام','رقم فاتورة المورد','المورد','قبل الضريبة','الضريبة','الإجمالي','الحالة','إجراءات'],rows)}`}
function returns(){let sup=state.data.suppliers.map(s=>s.name);let opts=['مرتجعات من فاتورة مشتريات','إشعار خصم','خصم إكسبير','خصم فروقات أسعار','خصم تسوية رصيد'];let rows=state.data.returns.map(r=>`<tr><td>${r.date}</td><td>${r.docNo||''}</td><td>${r.returnType}</td><td>${r.invoiceNo||''}</td><td>${r.supplier}</td><td>${fmt(r.beforeTax)}</td><td>${fmt(r.tax)}</td><td>${fmt(r.total)}</td><td>${badge(r.status)}</td><td>${actionBtns('returns',r)}</td></tr>`);$('#view').innerHTML=`<div class="toolbar"><button class="ok" onclick="excel('returns')">Excel</button></div><div class="card"><h3>مرتجع / خصم</h3><p class="hint">أنواع الحركة المطلوبة مضافة مع رقم فاتورة المورد وربط VAT تلقائي.</p>${inputRow([{k:'date',t:'التاريخ',type:'date'},{k:'supplier',type:'select',opts:sup},{k:'returnType',type:'select',opts},{k:'invoiceNo',t:'رقم الفاتورة'},{k:'beforeTax',t:'قبل الضريبة',type:'number'},{k:'tax',t:'VAT',type:'number'},{k:'notes',t:'ملاحظات'}],'ret')}<br><button class="muted" onclick="autoTax('ret')">حساب VAT</button><button class="primary" onclick="add('returns','ret')">حفظ كمسودة</button></div>${table(['التاريخ','رقم النظام','نوع الحركة','رقم فاتورة المورد','المورد','قبل الضريبة','الضريبة','الإجمالي','الحالة','إجراءات'],rows)}`}
function payments(){let sup=state.data.suppliers.map(s=>s.name);let rows=state.data.payments.map(r=>`<tr><td>${r.date}</td><td>${r.docNo||''}</td><td>${r.supplier}</td><td>${fmt(r.amount)}</td><td>${r.method||''}</td><td>${badge(r.status)}</td><td>${actionBtns('payments',r)}</td></tr>`);$('#view').innerHTML=`<div class="toolbar"><button class="ok" onclick="excel('payments')">Excel</button></div><div class="card"><h3>سداد مورد</h3>${inputRow([{k:'date',t:'التاريخ',type:'date'},{k:'supplier',type:'select',opts:sup},{k:'amount',t:'المبلغ',type:'number'},{k:'method',type:'select',opts:['الصندوق','البنك']},{k:'notes',t:'ملاحظات'}],'pay')}<br><button class="primary" onclick="add('payments','pay')">حفظ كمسودة</button></div>${table(['التاريخ','رقم السند','المورد','المبلغ','طريقة الدفع','الحالة','إجراءات'],rows)}`}
function statement(){let sup=state.data.suppliers.map(s=>s.name);$('#view').innerHTML=`<div class="card noPrint"><div class="grid"><select id="st_s">${sup.map(s=>`<option>${s}</option>`).join('')}</select><input id="st_from" type="date"><input id="st_to" type="date"><select id="st_type"><option>الكل</option><option>مشتريات</option><option>سداد</option><option>مرتجعات من فاتورة مشتريات</option><option>إشعار خصم</option><option>خصم إكسبير</option><option>خصم فروقات أسعار</option><option>خصم تسوية رصيد</option></select></div><br><button class="primary" onclick="loadStatement()">عرض</button><button class="ok" onclick="window.print()">طباعة / PDF</button></div><div id="statementResult" class="card">اختر المورد واضغط عرض</div>`}
async function loadStatement(){let q=new URLSearchParams({supplier:$('#st_s').value,from:$('#st_from').value,to:$('#st_to').value,type:$('#st_type').value});let d=await api('/api/supplier-statement?'+q);let rows=d.rows.map(r=>`<tr><td>${r.date}</td><td>${r.type}</td><td>${r.docNo}</td><td>${fmt(r.debit)}</td><td>${fmt(r.credit)}</td><td>${fmt(r.balance)}</td><td>${r.status||''}</td><td>${r.notes||''}</td></tr>`);$('#statementResult').innerHTML=`<h2>كشف حساب المورد</h2><h3>${d.supplier.name}</h3>${table(['التاريخ','نوع الحركة','رقم المستند','مدين','دائن','الرصيد','الحالة','ملاحظات'],rows)}<h3>الرصيد النهائي: ${fmt(d.balance)}</h3>`}
async function balances(){let data=await api('/api/supplier-balances');let rows=data.map(s=>`<tr><td>${s.name}</td><td>${fmt(s.opening)}</td><td>${fmt(s.balance)}</td><td>${s.balance==s.opening?'مطابق أول مدة فقط':'به حركات'}</td></tr>`);$('#view').innerHTML=`<div class="toolbar"><button class="ok" onclick="window.print()">PDF</button><button class="ok" onclick="excel('suppliers')">Excel</button></div>${table(['المورد','رصيد أول المدة','الرصيد الحالي','الحالة'],rows)}`}
function journals(){let rows=state.data.journals.map(j=>`<tr><td>${j.date}</td><td>${j.docNo}</td><td>${j.desc}</td><td>${j.debitAcc}</td><td>${fmt(j.debit)}</td><td>${j.creditAcc}</td><td>${fmt(j.credit)}</td><td>${j.source}</td></tr>`);$('#view').innerHTML=`<div class="toolbar"><button class="ok" onclick="excel('journals')">Excel</button></div>${table(['التاريخ','رقم','البيان','مدين','مبلغ','دائن','مبلغ','المصدر'],rows)}`}

async function vat(){
  $('#view').innerHTML=`<div class="card noPrint"><h3>تقرير ضريبة القيمة المضافة VAT</h3><div class="grid"><input id="vat_from" type="date"><input id="vat_to" type="date"></div><br><button class="primary" onclick="loadVat()">عرض التقرير</button><button class="ok" onclick="window.print()">طباعة / PDF</button><button class="ok" onclick="excel('vat')">Excel</button></div><div id="vatResult" class="card">اختر الفترة واضغط عرض</div>`;
}
async function loadVat(){let q=new URLSearchParams({from:$('#vat_from').value,to:$('#vat_to').value});let d=await api('/api/vat-report?'+q);let rows=d.rows.map(r=>`<tr><td>${r.type}</td><td>${r.date}</td><td>${r.docNo}</td><td>${r.supplier}</td><td>${fmt(r.beforeTax)}</td><td>${fmt(r.tax)}</td><td>${fmt(r.total)}</td></tr>`);$('#vatResult').innerHTML=`<div class="cards"><div class="card"><div class="metric">VAT مشتريات</div><div class="value">${fmt(d.purchaseVat)}</div></div><div class="card"><div class="metric">VAT خصومات/مرتجعات</div><div class="value">${fmt(d.returnVat)}</div></div><div class="card"><div class="metric">صافي VAT</div><div class="value">${fmt(d.netVat)}</div></div><div class="card"><div class="metric">النسبة</div><div class="value">${d.rate}%</div></div></div>${table(['النوع','التاريخ','رقم المستند','المورد','قبل الضريبة','VAT','الإجمالي'],rows)}`}

async function users(){
  if(!can('canSettings')) { $('#view').innerHTML='<div class="card">هذه الصفحة للمدير فقط.</div>'; return; }
  let list=await api('/api/users');
  let rows=list.map(u=>`<tr><td>${u.username}</td><td>${u.role}</td><td>${Object.entries(u.permissions||{}).filter(x=>x[1]).map(x=>x[0]).join(' - ')}</td><td><button class="muted" onclick="editUser('${u.username}','${u.role}')">تعديل الصلاحية/كلمة المرور</button>${u.username!=='admin'?`<button class="danger" onclick="deleteUser('${u.username}')">حذف</button>`:''}</td></tr>`);
  $('#view').innerHTML=`<div class="card"><h3>إضافة مستخدم جديد</h3><div class="grid"><input id="new_user" placeholder="اسم المستخدم"><input id="new_pass" placeholder="كلمة المرور" value="1234"><select id="new_role"><option>Admin</option><option>Accountant</option><option>Viewer</option></select></div><br><button class="primary" onclick="addUser()">إضافة مستخدم</button></div><div class="card"><h3>تغيير كلمة مرور المستخدم الحالي</h3><div class="grid"><input id="old_pass" type="password" placeholder="كلمة المرور الحالية"><input id="new_my_pass" type="password" placeholder="كلمة المرور الجديدة"></div><br><button class="ok" onclick="changeMyPassword()">تغيير كلمة مروري</button></div>${table(['المستخدم','الدور/الصلاحية','الصلاحيات المفعلة','إجراءات'],rows)}`;
}
async function addUser(){try{await api('/api/users',{method:'POST',body:{username:$('#new_user').value,password:$('#new_pass').value,role:$('#new_role').value}}); alert('تم إضافة المستخدم'); await render()}catch(e){alert(e.message)}}
async function editUser(username,role){let newRole=prompt('الصلاحية: Admin / Accountant / Viewer',role); if(!newRole)return; let pass=prompt('كلمة مرور جديدة - اتركها فارغة بدون تغيير',''); let body={role:newRole}; if(pass) body.password=pass; try{await api('/api/users/'+encodeURIComponent(username),{method:'PUT',body}); alert('تم تعديل المستخدم'); await render()}catch(e){alert(e.message)}}
async function deleteUser(username){if(!confirm('حذف المستخدم '+username+'؟'))return; try{await api('/api/users/'+encodeURIComponent(username),{method:'DELETE'}); alert('تم الحذف'); await render()}catch(e){alert(e.message)}}
async function changeMyPassword(){try{await api('/api/change-password',{method:'POST',body:{oldPassword:$('#old_pass').value,newPassword:$('#new_my_pass').value}}); alert('تم تغيير كلمة المرور، سجل الدخول مرة أخرى'); logout()}catch(e){alert(e.message)}}

function settings(){let st=state.data.settings||{};let acc=st.accounts||{}, num=st.numbering||{}, perms=st.permissions||{}; if(!can('canSettings')) { $('#view').innerHTML='<div class="card">هذه الصفحة للمدير فقط.</div>'; return; } $('#view').innerHTML=`<div class="card"><h3>VAT</h3><div class="grid"><input id="set_vatRate" type="number" value="${st.vatRate||15}" placeholder="نسبة VAT"><select id="set_autoVat"><option value="true" ${st.autoVat?'selected':''}>احتساب VAT تلقائي</option><option value="false" ${!st.autoVat?'selected':''}>إدخال VAT يدوي فقط</option></select></div></div><div class="card"><h3>ربط القيود التلقائية بالحسابات</h3><div class="grid">${['purchases','inputVat','suppliers','returns','discounts','cash','bank','opening'].map(k=>`<input id="acc_${k}" value="${acc[k]||''}" placeholder="${k}">`).join('')}</div></div><div class="card"><h3>ترقيم المستندات</h3><div class="grid">${['PUR','RET','PAY','JRN'].map(k=>`<input id="num_${k}" value="${(num[k]||{}).prefix||k}" placeholder="Prefix ${k}">`).join('')}</div></div><div class="card"><h3>الصلاحيات التفصيلية</h3><p class="hint">1 = مسموح، 0 = ممنوع</p>${['Admin','Accountant','Viewer'].map(role=>`<h4>${role}</h4><div class="grid">${['add','edit','delete','approve','post','cancel','close','open','import','export','settings','attachments'].map(k=>`<label>${k}<input id="perm_${role}_${k}" value="${(perms[role]||{})[k]?1:0}"></label>`).join('')}</div>`).join('')}</div><button class="primary" onclick="saveSettings()">حفظ الإعدادات</button>`}
async function saveSettings(){let accounts={}; ['purchases','inputVat','suppliers','returns','discounts','cash','bank','opening'].forEach(k=>accounts[k]=$('#acc_'+k).value); let numbering={}; ['PUR','RET','PAY','JRN'].forEach(k=>numbering[k]={prefix:$('#num_'+k).value,name:k}); let permissions={}; ['Admin','Accountant','Viewer'].forEach(role=>{permissions[role]={}; ['add','edit','delete','approve','post','cancel','close','open','import','export','settings','attachments'].forEach(k=>permissions[role][k]=$('#perm_'+role+'_'+k).value==='1')}); try{await api('/api/settings',{method:'PUT',body:{vatRate:Number($('#set_vatRate').value||15),autoVat:$('#set_autoVat').value==='true',accounts,numbering,permissions}}); alert('تم حفظ إعدادات VAT وربط القيود والصلاحيات والترقيم'); await render()}catch(e){alert(e.message)}}

function workflow(){let docs=[...state.data.purchases.map(x=>({...x,_t:'purchases',_name:'شراء'})),...state.data.returns.map(x=>({...x,_t:'returns',_name:'مرتجع/خصم'})),...state.data.payments.map(x=>({...x,_t:'payments',_name:'سداد'}))].sort((a,b)=>(b.date||'').localeCompare(a.date||''));let rows=docs.map(r=>`<tr><td>${r._name}</td><td>${r.date}</td><td>${r.invoiceNo||r.docNo}</td><td>${r.supplier}</td><td>${fmt(r.total||r.amount)}</td><td>${badge(r.status)}</td><td>${r.createdBy||''}</td><td>${r.approvedBy||r.postedBy||''}</td><td>${actionBtns(r._t,r)}</td></tr>`);$('#view').innerHTML=table(['النوع','التاريخ','رقم المستند','المورد','المبلغ','الحالة','أنشأه','اعتمده/رحله','إجراءات'],rows)}
function attachBox(tableName,id){go('attachments').then(()=>{setTimeout(()=>{$('#att_table').value=tableName;$('#att_id').value=id},100)})}
function attachments(){let rows=state.data.attachments.map(a=>`<tr><td>${a.table}</td><td>${a.recordId}</td><td><a href="/api/attachment/${a.id}" target="_blank">${a.name}</a></td><td>${a.uploadedBy}</td><td>${a.uploadedAt}</td><td>${a.notes||''}</td></tr>`);$('#view').innerHTML=`<div class="card"><h3>إضافة مرفق لفاتورة أو سند</h3><div class="grid"><select id="att_table"><option>purchases</option><option>returns</option><option>payments</option><option>suppliers</option></select><input id="att_id" placeholder="رقم ID للمستند"><input id="att_notes" placeholder="ملاحظات"><input class="wide filebox" id="att_file" type="file"></div><br><button class="primary" onclick="uploadAttachment()">رفع المرفق</button></div>${table(['الصفحة','رقم السجل','الملف','رفع بواسطة','التاريخ','ملاحظات'],rows)}`}
async function uploadAttachment(){let f=$('#att_file').files[0]; if(!f) return alert('اختر ملف'); let reader=new FileReader(); reader.onload=async()=>{try{await api('/api/upload-attachment',{method:'POST',body:{table:$('#att_table').value,recordId:$('#att_id').value,name:f.name,type:f.type,size:f.size,notes:$('#att_notes').value,data:reader.result}}); await render()}catch(e){alert(e.message)}}; reader.readAsDataURL(f)}
function locks(){let rows=(state.data.lockedMonths||[]).map(m=>`<tr><td>${m.month}</td><td>${m.lockedBy}</td><td>${m.lockedAt}</td><td>${m.notes||''}</td><td>${can('canOpen')?`<button class="danger" onclick="unlockMonth('${m.month}')">فتح</button>`:''}</td></tr>`);$('#view').innerHTML=`<div class="card"><h3>إقفال شهر</h3><div class="grid"><input id="lm" type="month"><input id="ln" placeholder="ملاحظات"></div><br><button class="primary" onclick="lockMonth()">إقفال الشهر</button></div>${table(['الشهر','بواسطة','التاريخ','ملاحظات','إجراء'],rows)}`}
async function lockMonth(){try{await api('/api/lock-month',{method:'POST',body:{month:$('#lm').value,notes:$('#ln').value}});await render()}catch(e){alert(e.message)}} async function unlockMonth(m){try{await api('/api/unlock-month/'+m,{method:'DELETE'});await render()}catch(e){alert(e.message)}}
function audit(){let rows=(state.data.auditLog||[]).map(a=>`<tr><td>${a.at}</td><td>${a.user}</td><td>${a.role}</td><td>${a.action}</td><td>${a.table}</td><td>${a.recordId}</td><td>${a.note||''}</td></tr>`);$('#view').innerHTML=table(['التاريخ','المستخدم','الصلاحية','العملية','الصفحة','رقم السجل','ملاحظة'],rows)}
function backup(){$('#view').innerHTML=`<div class="card"><div class="toolbar"><button class="ok" onclick="exportJSON()">تصدير Backup JSON</button><button class="ok" onclick="excel('suppliers')">Excel الموردين</button><button class="ok" onclick="excel('purchases')">Excel المشتريات</button><button class="ok" onclick="excel('returns')">Excel المرتجعات</button><button class="ok" onclick="excel('payments')">Excel المدفوعات</button><button class="ok" onclick="excel('journals')">Excel القيود</button></div><textarea id="imp" rows="10" placeholder="الصق ملف JSON هنا للاستيراد"></textarea><br><button class="primary" onclick="importJSON()">استيراد JSON</button></div>`}
async function exportJSON(){let d=await api('/api/export');let blob=new Blob([JSON.stringify(d,null,2)],{type:'application/json'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='AMS_ERP_FINAL_BACKUP_'+Date.now()+'.json';a.click()} async function importJSON(){try{await api('/api/import',{method:'POST',body:JSON.parse($('#imp').value)});alert('تم الاستيراد');await render()}catch(e){alert(e.message)}}
function excel(name){location.href='/api/export-excel/'+name}
function smartSearch(v){v=(v||'').trim(); if(!v)return; let all=[...state.data.suppliers.map(x=>['مورد',x.name,x.opening]),...state.data.purchases.map(x=>['شراء',x.supplier,x.invoiceNo||x.docNo]),...state.data.returns.map(x=>['مرتجع',x.supplier,x.invoiceNo||x.docNo]),...state.data.payments.map(x=>['سداد',x.supplier,x.docNo])].filter(x=>String(x.join(' ')).includes(v)); $('#notice').innerHTML=all.slice(0,8).map(x=>`<span class="badge">${x.join(' - ')}</span>`).join(' ')||'لا توجد نتائج';}
render();
