const http = require('http');
const fs = require('fs');
const path = require('path');
const url = require('url');
const PORT = 3000;
const DB_FILE = path.join(__dirname, 'database.json');
const PUBLIC = path.join(__dirname, 'public');
const ATTACH_DIR = path.join(__dirname, 'attachments');
if(!fs.existsSync(ATTACH_DIR)) fs.mkdirSync(ATTACH_DIR);
const defaultUsers = {
  admin: { password:'1234', role:'Admin' },
  accountant: { password:'1234', role:'Accountant' },
  viewer: { password:'1234', role:'Viewer' }
};
const defaultPerms = {
  Admin: { add:true, edit:true, delete:true, approve:true, post:true, cancel:true, close:true, open:true, import:true, export:true, settings:true, attachments:true },
  Accountant: { add:true, edit:true, delete:false, approve:false, post:false, cancel:false, close:false, open:false, import:false, export:true, settings:false, attachments:true },
  Viewer: { add:false, edit:false, delete:false, approve:false, post:false, cancel:false, close:false, open:false, import:false, export:true, settings:false, attachments:false }
};
function defaultSettings(){ return { company:'صيدلية عبد العزيز المركزية', currency:'SAR', vatRate:15, autoVat:true, vatIncluded:false, accounts:{ purchases:'المشتريات', inputVat:'ضريبة القيمة المضافة - مدخلات', suppliers:'الموردون', returns:'مردودات ومسموحات مشتريات', discounts:'خصومات مكتسبة', cash:'الصندوق', bank:'البنك', opening:'أرصدة افتتاحية' }, numbering:{ PUR:{prefix:'PUR',name:'فاتورة شراء'}, RET:{prefix:'RET',name:'مرتجع/خصم'}, PAY:{prefix:'PAY',name:'سند صرف'}, JRN:{prefix:'JRN',name:'قيد يومية'} }, permissions: defaultPerms }; }
function readDB(){ const db=JSON.parse(fs.readFileSync(DB_FILE,'utf8')); db.suppliers=db.suppliers||[]; db.purchases=db.purchases||[]; db.returns=db.returns||[]; db.payments=db.payments||[]; db.journals=db.journals||[]; db.assets=db.assets||[]; db.lockedMonths=db.lockedMonths||[]; db.auditLog=db.auditLog||[]; db.attachments=db.attachments||[]; db.documentCounters=db.documentCounters||{}; db.settings={...defaultSettings(), ...(db.settings||{}), accounts:{...defaultSettings().accounts, ...((db.settings||{}).accounts||{})}, numbering:{...defaultSettings().numbering, ...((db.settings||{}).numbering||{})}, permissions:{...defaultPerms, ...((db.settings||{}).permissions||{})} }; if(!db.users || Array.isArray(db.users)) db.users=defaultUsers; return db; }
function saveDB(db){ fs.writeFileSync(DB_FILE, JSON.stringify(db,null,2),'utf8'); }
function send(res,status,data,type='application/json',headers={}){ res.writeHead(status, {'Content-Type': type+'; charset=utf-8',...headers}); res.end(type==='application/json'?JSON.stringify(data):data); }
function body(req){ return new Promise(resolve=>{ let b=''; req.on('data',c=>{b+=c; if(b.length>30_000_000) req.destroy();}); req.on('end',()=>{ try{resolve(b?JSON.parse(b):{})}catch{resolve({})} }); }); }
function getUser(req,db){ const uname=req.headers['x-user']||''; const rec=(db.users||defaultUsers)[uname]; if(!rec) return null; const perms=(db.settings?.permissions||defaultPerms)[rec.role]||{}; return {name:uname,...rec, canAdd:!!perms.add, canEdit:!!perms.edit, canDelete:!!perms.delete, canClose:!!perms.close, canOpen:!!perms.open, canImport:!!perms.import, canApprove:!!perms.approve, canPost:!!perms.post, canCancel:!!perms.cancel, canAttach:!!perms.attachments, canExport:!!perms.export, canSettings:!!perms.settings, perm:perms}; }
function ym(date){ return String(date||'').slice(0,7); }
function isLocked(db,date){ return !!date && db.lockedMonths.some(m=>m.month===ym(date)); }
function audit(db,user,action,table,id,before,after,note=''){ db.auditLog.unshift({ id:Date.now()+Math.random(), at:new Date().toISOString(), user:user?.name||'system', role:user?.role||'', action, table, recordId:id||'', before:before||null, after:after||null, note }); }
function can(res,user,perm){ if(!user){send(res,401,{error:'غير مسجل دخول'}); return false;} if(!user[perm]){send(res,403,{error:'لا توجد صلاحية لتنفيذ العملية'}); return false;} return true; }
function nextNo(db,prefix,date){ const d=date?new Date(date):new Date(); const y=d.getFullYear(); const m=String(d.getMonth()+1).padStart(2,'0'); const conf=(db.settings.numbering||{})[prefix]||{prefix}; const pfx=conf.prefix||prefix; const key=pfx+'-'+y+'-'+m; db.documentCounters[key]=(db.documentCounters[key]||0)+1; return pfx+'-'+y+m+'-'+String(db.documentCounters[key]).padStart(5,'0'); }
function applyVat(db,b){ const rate=n(db.settings.vatRate); const before=n(b.beforeTax); if(db.settings.autoVat && (b.tax==='' || b.tax===undefined || b.tax===null)){ b.tax=+(before*rate/100).toFixed(2); } b.total=+(n(b.beforeTax)+n(b.tax)).toFixed(2); return b; }
function n(v){ return Number(v||0); }
function supplierBalance(db,s){ const name=s.name; let bal=n(s.opening); db.purchases.filter(x=>x.status!=='ملغي').forEach(x=>{ if(x.supplier===name) bal+=n(x.total); }); db.returns.filter(x=>x.status!=='ملغي').forEach(x=>{ if(x.supplier===name) bal-=n(x.total); }); db.payments.filter(x=>x.status!=='ملغي').forEach(x=>{ if(x.supplier===name) bal-=n(x.amount); }); return bal; }
function postJournal(db,user,source,row){ db.journals.unshift({id:Date.now()+Math.random(), status:'مرحل', source, createdBy:user?.name||'system', createdAt:new Date().toISOString(), ...row}); audit(db,user,'AUTO_JOURNAL','journals',row.docNo,null,row,'ترحيل تلقائي'); }
function removeSourceJournals(db,source,id){ db.journals=db.journals.filter(j=>!(j.source===source && String(j.sourceId)===String(id))); }
function journalFor(db,user,table,doc){ const acc=db.settings.accounts; removeSourceJournals(db,table,doc.id); if(doc.status==='ملغي') return; if(table==='purchases') postJournal(db,user,table,{sourceId:doc.id,date:doc.date,docNo:doc.docNo||doc.invoiceNo,desc:'فاتورة شراء - '+doc.supplier+' / فاتورة خارجية: '+(doc.invoiceNo||''),debitAcc:n(doc.tax)>0?acc.purchases+' + '+acc.inputVat:acc.purchases,creditAcc:acc.suppliers,debit:n(doc.total),credit:n(doc.total),vat:n(doc.tax),beforeTax:n(doc.beforeTax)}); if(table==='returns') postJournal(db,user,table,{sourceId:doc.id,date:doc.date,docNo:doc.docNo||doc.invoiceNo,desc:(doc.returnType||'مرتجع')+' - '+doc.supplier+' / فاتورة خارجية: '+(doc.invoiceNo||''),debitAcc:acc.suppliers,creditAcc:(doc.returnType||'').includes('خصم')?acc.discounts:acc.returns,debit:n(doc.total),credit:n(doc.total),vat:n(doc.tax),beforeTax:n(doc.beforeTax)}); if(table==='payments') postJournal(db,user,table,{sourceId:doc.id,date:doc.date,docNo:doc.docNo,desc:'سداد مورد - '+doc.supplier,debitAcc:acc.suppliers,creditAcc:(doc.method==='البنك'?acc.bank:acc.cash),debit:n(doc.amount),credit:n(doc.amount)}); }
function htmlEscape(s){ return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
function excelHtml(title, heads, rows){ return `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><style>table{border-collapse:collapse}td,th{border:1px solid #999;padding:6px}th{background:#d9eaf7}</style></head><body><h2>${htmlEscape(title)}</h2><table><thead><tr>${heads.map(h=>`<th>${htmlEscape(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${htmlEscape(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></body></html>`; }
function createOpeningJournal(db,user,force=false){ if(db.openingJournalCreated && !force) return {created:false,message:'القيد الافتتاحي موجود بالفعل'}; db.journals=db.journals.filter(j=>j.source!=='opening'); const total=db.suppliers.reduce((a,s)=>a+n(s.opening),0); const rows=db.suppliers.filter(s=>n(s.opening)!==0).map(s=>({supplier:s.name,amount:n(s.opening)})); const docNo='OPEN-'+new Date().getFullYear(); postJournal(db,user,'opening',{sourceId:'opening',date:new Date().toISOString().slice(0,10),docNo,desc:'قيد افتتاحي تلقائي من أرصدة الموردين',debitAcc:total<0?db.settings.accounts.suppliers:db.settings.accounts.opening,creditAcc:total>=0?db.settings.accounts.suppliers:db.settings.accounts.opening,debit:Math.abs(total),credit:Math.abs(total),details:rows}); db.openingJournalCreated=true; audit(db,user,'CREATE_OPENING_JOURNAL','journals',docNo,null,{total,rows},'قيد افتتاحي تلقائي'); return {created:true,total,rows}; }
const server=http.createServer(async(req,res)=>{
  const parsed=url.parse(req.url,true); const method=req.method; const pathname=decodeURIComponent(parsed.pathname);
  if(pathname.startsWith('/api/')){
    const db=readDB(); const user=getUser(req,db);
    if(pathname==='/api/login' && method==='POST'){ const b=await body(req); const u=(db.users||defaultUsers)[b.username]; if(u && u.password===b.password){ const gu=getUser({headers:{'x-user':b.username}},db); return send(res,200,{username:b.username,role:u.role,permissions:gu}); } return send(res,401,{error:'بيانات الدخول غير صحيحة'}); }
    if(pathname==='/api/users-public' && method==='GET'){ const users=db.users||defaultUsers; return send(res,200,Object.keys(users).map(username=>({username,role:users[username].role}))); }
    if(!user) return send(res,401,{error:'غير مسجل دخول'});
    if(pathname==='/api/data') return send(res,200,db);
    if(pathname==='/api/users' && method==='GET'){ if(!can(res,user,'canSettings')) return; const users=db.users||defaultUsers; return send(res,200,Object.keys(users).map(username=>({username,role:users[username].role,permissions:(db.settings.permissions||defaultPerms)[users[username].role]||{}}))); }
    if(pathname==='/api/users' && method==='POST'){ if(!can(res,user,'canSettings')) return; const b=await body(req); const username=String(b.username||'').trim(); if(!username) return send(res,400,{error:'اكتب اسم المستخدم'}); db.users=db.users||defaultUsers; if(db.users[username]) return send(res,400,{error:'المستخدم موجود بالفعل'}); db.users[username]={password:String(b.password||'1234'), role:b.role||'Viewer'}; audit(db,user,'CREATE_USER','users',username,null,{username,role:db.users[username].role},'إنشاء مستخدم جديد'); saveDB(db); return send(res,200,{username,role:db.users[username].role}); }
    if(pathname.startsWith('/api/users/') && method==='PUT'){ if(!can(res,user,'canSettings')) return; const username=decodeURIComponent(pathname.split('/').pop()); const b=await body(req); db.users=db.users||defaultUsers; if(!db.users[username]) return send(res,404,{error:'المستخدم غير موجود'}); const before={username,...db.users[username]}; if(b.role) db.users[username].role=b.role; if(b.password) db.users[username].password=String(b.password); audit(db,user,'UPDATE_USER','users',username,before,{username,...db.users[username]},'تعديل مستخدم أو كلمة المرور أو الصلاحية'); saveDB(db); return send(res,200,{username,role:db.users[username].role}); }
    if(pathname.startsWith('/api/users/') && method==='DELETE'){ if(!can(res,user,'canSettings')) return; const username=decodeURIComponent(pathname.split('/').pop()); if(username==='admin') return send(res,400,{error:'لا يمكن حذف admin'}); db.users=db.users||defaultUsers; const before=db.users[username]; if(!before) return send(res,404,{error:'المستخدم غير موجود'}); delete db.users[username]; audit(db,user,'DELETE_USER','users',username,before,null,'حذف مستخدم'); saveDB(db); return send(res,200,{ok:true}); }
    if(pathname==='/api/change-password' && method==='POST'){ const b=await body(req); db.users=db.users||defaultUsers; const rec=db.users[user.name]; if(!rec || rec.password!==b.oldPassword) return send(res,400,{error:'كلمة المرور الحالية غير صحيحة'}); if(!b.newPassword || String(b.newPassword).length<4) return send(res,400,{error:'كلمة المرور الجديدة لا تقل عن 4 أحرف'}); const before={username:user.name,role:rec.role}; rec.password=String(b.newPassword); audit(db,user,'CHANGE_PASSWORD','users',user.name,before,{username:user.name,role:rec.role},'تغيير كلمة مرور المستخدم الحالي'); saveDB(db); return send(res,200,{ok:true}); }
    if(pathname==='/api/settings' && method==='GET') return send(res,200,db.settings);
    if(pathname==='/api/settings' && method==='PUT'){ if(!can(res,user,'canSettings')) return; const b=await body(req); const before=JSON.parse(JSON.stringify(db.settings)); db.settings={...db.settings,...b, accounts:{...db.settings.accounts,...(b.accounts||{})}, numbering:{...db.settings.numbering,...(b.numbering||{})}, permissions:{...db.settings.permissions,...(b.permissions||{})}}; audit(db,user,'UPDATE_SETTINGS','settings','general',before,db.settings,'تحديث إعدادات VAT والقيود والصلاحيات والترقيم'); saveDB(db); return send(res,200,db.settings);}
    if(pathname==='/api/vat-report'){ const from=parsed.query.from||'', to=parsed.query.to||''; const inRange=x=>(!from||x.date>=from)&&(!to||x.date<=to)&&x.status!=='ملغي'; const pur=db.purchases.filter(inRange).reduce((a,x)=>a+n(x.tax),0); const ret=db.returns.filter(inRange).reduce((a,x)=>a+n(x.tax),0); return send(res,200,{from,to,purchaseVat:pur,returnVat:ret,netVat:pur-ret,rate:db.settings.vatRate,rows:[...db.purchases.filter(inRange).map(x=>({type:'ضريبة مشتريات',date:x.date,docNo:x.invoiceNo||x.docNo,supplier:x.supplier,beforeTax:x.beforeTax,tax:x.tax,total:x.total})),...db.returns.filter(inRange).map(x=>({type:'ضريبة خصم/مرتجع',date:x.date,docNo:x.invoiceNo||x.docNo,supplier:x.supplier,beforeTax:x.beforeTax,tax:x.tax,total:x.total}))]}); }
    if(pathname==='/api/dashboard'){ const purchases=db.purchases.filter(x=>x.status!=='ملغي').reduce((a,b)=>a+n(b.total),0), returns=db.returns.filter(x=>x.status!=='ملغي').reduce((a,b)=>a+n(b.total),0), payments=db.payments.filter(x=>x.status!=='ملغي').reduce((a,b)=>a+n(b.amount),0); const opening=db.suppliers.reduce((a,b)=>a+n(b.opening),0), supplierTotal=db.suppliers.reduce((a,s)=>a+supplierBalance(db,s),0); return send(res,200,{suppliers:db.suppliers.length,opening,purchases,returns,payments,supplierTotal,locked:db.lockedMonths.length,audit:db.auditLog.length,attachments:db.attachments.length,drafts:[...db.purchases,...db.returns,...db.payments].filter(x=>x.status==='مسودة').length,approved:[...db.purchases,...db.returns,...db.payments].filter(x=>x.status==='معتمد').length}); }
    if(pathname==='/api/supplier-balances') return send(res,200,db.suppliers.map(s=>({...s,balance:supplierBalance(db,s)})));
    if(pathname==='/api/supplier-statement'){ const q=parsed.query; const supplier=q.supplier||''; const s=db.suppliers.find(x=>x.name===supplier); if(!s) return send(res,404,{error:'المورد غير موجود'}); let rows=[{date:q.from||'', type:'رصيد أول المدة', docNo:'OPEN', debit:n(s.opening)>0?n(s.opening):0, credit:n(s.opening)<0?Math.abs(n(s.opening)):0, notes:'رصيد افتتاحي'}]; db.purchases.filter(x=>x.status!=='ملغي'&&x.supplier===supplier).forEach(x=>rows.push({date:x.date,type:'مشتريات',docNo:x.invoiceNo||x.docNo,debit:n(x.total),credit:0,notes:x.notes||'',status:x.status})); db.returns.filter(x=>x.status!=='ملغي'&&x.supplier===supplier).forEach(x=>rows.push({date:x.date,type:x.returnType||'مرتجع',docNo:x.invoiceNo||x.docNo,debit:0,credit:n(x.total),notes:x.notes||'',status:x.status})); db.payments.filter(x=>x.status!=='ملغي'&&x.supplier===supplier).forEach(x=>rows.push({date:x.date,type:'سداد',docNo:x.docNo,debit:0,credit:n(x.amount),notes:x.notes||'',status:x.status})); rows=rows.filter(r=>(!q.from||!r.date||r.date>=q.from)&&(!q.to||!r.date||r.date<=q.to)&&(!q.type||q.type==='الكل'||r.type===q.type)); rows.sort((a,b)=>(a.date||'0000').localeCompare(b.date||'0000')); let run=0; rows=rows.map(r=>{run+=n(r.debit)-n(r.credit); return {...r,balance:run};}); return send(res,200,{supplier:s,rows,balance:run}); }
    if(pathname==='/api/create-opening-journal' && method==='POST'){ if(!can(res,user,'canApprove')) return; const q=parsed.query; const result=createOpeningJournal(db,user,q.force==='1'); saveDB(db); return send(res,200,result); }
    if(pathname.startsWith('/api/workflow/') && method==='POST'){ const partsTmp=pathname.split('/'); const actionTmp=partsTmp[5]; if(actionTmp==='post'){ if(!can(res,user,'canPost')) return; } else if(!can(res,user,'canApprove')) return; const parts=pathname.split('/'); const table=parts[3], id=parts[4], action=parts[5]; if(!['purchases','returns','payments'].includes(table)) return send(res,400,{error:'صفحة غير صحيحة'}); const row=db[table].find(x=>String(x.id)===String(id)); if(!row) return send(res,404,{error:'المستند غير موجود'}); if(row.date&&isLocked(db,row.date)) return send(res,423,{error:'الشهر مقفل'}); const before=JSON.parse(JSON.stringify(row)); if(action==='approve'){ row.status='معتمد'; row.approvedBy=user.name; row.approvedAt=new Date().toISOString(); journalFor(db,user,table,row); audit(db,user,'APPROVE',table,id,before,row,'اعتماد مستند'); } else if(action==='post'){ row.status='مرحل'; row.postedBy=user.name; row.postedAt=new Date().toISOString(); journalFor(db,user,table,row); audit(db,user,'POST',table,id,before,row,'ترحيل مستند'); } else if(action==='cancel'){ if(!can(res,user,'canCancel')) return; row.status='ملغي'; row.cancelledBy=user.name; row.cancelledAt=new Date().toISOString(); row.cancelReason=(await body(req)).reason||''; removeSourceJournals(db,table,id); audit(db,user,'CANCEL',table,id,before,row,'إلغاء مستند بدل الحذف'); } else return send(res,400,{error:'إجراء غير صحيح'}); saveDB(db); return send(res,200,row); }
    if(pathname==='/api/upload-attachment' && method==='POST'){ if(!can(res,user,'canAttach')) return; const b=await body(req); if(!b.table||!b.recordId||!b.name||!b.data) return send(res,400,{error:'بيانات المرفق ناقصة'}); const safe=String(b.name).replace(/[\\/:*?"<>|]/g,'_'); const id=Date.now()+Math.random(); const ext=safe.includes('.')?safe.split('.').pop():'bin'; const fn=String(id).replace('.','_')+'.'+ext; const raw=String(b.data).split(',').pop(); fs.writeFileSync(path.join(ATTACH_DIR,fn),Buffer.from(raw,'base64')); const rec={id,table:b.table,recordId:String(b.recordId),name:safe,file:fn,type:b.type||'',size:b.size||0,uploadedBy:user.name,uploadedAt:new Date().toISOString(),notes:b.notes||''}; db.attachments.unshift(rec); audit(db,user,'ATTACH',b.table,b.recordId,null,rec,'إضافة مرفق'); saveDB(db); return send(res,200,rec); }
    if(pathname.startsWith('/api/attachment/')){ const id=pathname.split('/').pop(); const a=db.attachments.find(x=>String(x.id)===String(id)); if(!a) return send(res,404,{error:'المرفق غير موجود'}); const fp=path.join(ATTACH_DIR,a.file); if(!fs.existsSync(fp)) return send(res,404,{error:'الملف غير موجود'}); res.writeHead(200, {'Content-Type': a.type||'application/octet-stream','Content-Disposition':'inline; filename="'+encodeURIComponent(a.name)+'"'}); return fs.createReadStream(fp).pipe(res); }
    if(pathname.startsWith('/api/export-excel/')){ if(!can(res,user,'canExport')) return; const name=pathname.split('/').pop(); let heads=[], rows=[], title=name; if(name==='suppliers'){title='تقرير الموردين'; heads=['المورد','الجوال','الضريبي','رصيد أول المدة','الرصيد الحالي']; rows=db.suppliers.map(s=>[s.name,s.phone||'',s.tax||'',s.opening,supplierBalance(db,s)]);} if(name==='purchases'){title='تقرير المشتريات'; heads=['التاريخ','رقم الفاتورة','المورد','قبل الضريبة','الضريبة','الإجمالي','الحالة']; rows=db.purchases.map(x=>[x.date,x.invoiceNo||x.docNo,x.supplier,x.beforeTax,x.tax,x.total,x.status]);} if(name==='returns'){title='تقرير المرتجعات والخصومات'; heads=['التاريخ','النوع','رقم الفاتورة','المورد','الإجمالي','الحالة']; rows=db.returns.map(x=>[x.date,x.returnType,x.invoiceNo||x.docNo,x.supplier,x.total,x.status]);} if(name==='payments'){title='تقرير المدفوعات'; heads=['التاريخ','رقم السند','المورد','المبلغ','الطريقة','الحالة']; rows=db.payments.map(x=>[x.date,x.docNo,x.supplier,x.amount,x.method,x.status]);} if(name==='journals'){title='القيود اليومية'; heads=['التاريخ','رقم المستند','البيان','مدين','المبلغ','دائن','المبلغ']; rows=db.journals.map(j=>[j.date,j.docNo,j.desc,j.debitAcc,j.debit,j.creditAcc,j.credit]);} if(name==='vat'){title='تقرير ضريبة القيمة المضافة'; heads=['النوع','التاريخ','رقم المستند','المورد','قبل الضريبة','الضريبة','الإجمالي']; rows=[...db.purchases.map(x=>['ضريبة مشتريات',x.date,x.invoiceNo||x.docNo,x.supplier,x.beforeTax,x.tax,x.total]),...db.returns.map(x=>['ضريبة خصم/مرتجع',x.date,x.invoiceNo||x.docNo,x.supplier,x.beforeTax,x.tax,x.total])];} if(!heads.length) return send(res,404,{error:'تقرير غير موجود'}); return send(res,200,excelHtml(title,heads,rows),'application/vnd.ms-excel',{'Content-Disposition':'attachment; filename="'+name+'.xls"'}); }
    if(pathname==='/api/lock-month' && method==='POST'){ if(!can(res,user,'canClose')) return; const b=await body(req); if(!b.month) return send(res,400,{error:'اختر الشهر'}); if(!db.lockedMonths.some(x=>x.month===b.month)){ db.lockedMonths.unshift({month:b.month,lockedBy:user.name,lockedAt:new Date().toISOString(),notes:b.notes||''}); audit(db,user,'LOCK_MONTH','lockedMonths',b.month,null,b,'إقفال شهر'); saveDB(db);} return send(res,200,{ok:true}); }
    if(pathname.startsWith('/api/unlock-month/') && method==='DELETE'){ if(!can(res,user,'canOpen')) return; const month=pathname.split('/').pop(); const before=db.lockedMonths.find(x=>x.month===month); db.lockedMonths=db.lockedMonths.filter(x=>x.month!==month); audit(db,user,'UNLOCK_MONTH','lockedMonths',month,before,null,'فتح شهر'); saveDB(db); return send(res,200,{ok:true}); }
    const listMatch=pathname.match(/^\/api\/(suppliers|purchases|payments|returns|journals|auditLog|attachments)$/); if(listMatch){ const table=listMatch[1]; if(method==='GET') return send(res,200,db[table]||[]); if(method==='POST'){ if(!can(res,user,'canAdd')) return; const b=await body(req); if(b.date&&isLocked(db,b.date)) return send(res,423,{error:'الشهر مقفل'}); b.id=b.id||Date.now(); b.status=b.status||'مسودة'; b.createdBy=user.name; b.createdAt=new Date().toISOString(); if(table==='purchases'){ b.docNo=b.docNo||nextNo(db,'PUR',b.date); applyVat(db,b); } if(table==='returns'){ b.docNo=b.docNo||nextNo(db,'RET',b.date); applyVat(db,b); } if(table==='payments'){ b.docNo=b.docNo||nextNo(db,'PAY',b.date); b.amount=n(b.amount); } db[table].unshift(b); audit(db,user,'ADD_DRAFT',table,b.id,null,b,'إضافة مسودة'); saveDB(db); return send(res,200,b); } }
    const editMatch=pathname.match(/^\/api\/(suppliers|purchases|payments|returns)\/(.+)$/); if(editMatch){ const table=editMatch[1], id=editMatch[2]; const idx=db[table].findIndex(x=>String(x.id)===String(id)); if(idx<0) return send(res,404,{error:'السجل غير موجود'}); const before=JSON.parse(JSON.stringify(db[table][idx])); if((method==='PUT'||method==='DELETE')&&before.date&&isLocked(db,before.date)) return send(res,423,{error:'الشهر مقفل'}); if(method==='PUT'){ if(!can(res,user,'canEdit')) return; if(before.status&&before.status!=='مسودة'&&!user.canApprove) return send(res,403,{error:'المستند معتمد/مرحل ولا يعدله إلا Admin'}); const b=await body(req); const after={...db[table][idx],...b,updatedBy:user.name,updatedAt:new Date().toISOString()}; if(after.date&&isLocked(db,after.date)) return send(res,423,{error:'الشهر الجديد مقفل'}); if(table==='purchases'||table==='returns') applyVat(db,after); if(table==='payments') after.amount=n(after.amount); db[table][idx]=after; if(after.status&&after.status!=='مسودة') journalFor(db,user,table,after); audit(db,user,'EDIT',table,id,before,after); saveDB(db); return send(res,200,after); } if(method==='DELETE'){ if(!can(res,user,'canDelete')) return; if(before.status&&before.status!=='مسودة') return send(res,403,{error:'لا يتم حذف مستند معتمد، استخدم إلغاء المستند'}); db[table].splice(idx,1); audit(db,user,'DELETE',table,id,before,null); saveDB(db); return send(res,200,{ok:true}); } }
    if(pathname==='/api/export') return send(res,200,db);
    if(pathname==='/api/import' && method==='POST'){ if(!can(res,user,'canImport')) return; const b=await body(req); audit(b,user,'IMPORT','database','all',db,b,'استيراد قاعدة بيانات'); saveDB(b); return send(res,200,{ok:true}); }
    return send(res,404,{error:'API not found'});
  }
  let file=pathname==='/'?'index.html':pathname.slice(1); let fp=path.join(PUBLIC,file); if(!fp.startsWith(PUBLIC)) return send(res,403,'Forbidden','text/plain'); fs.readFile(fp,(err,data)=>{ if(err) return send(res,404,'Not found','text/plain'); const ext=path.extname(fp); const type=ext==='.html'?'text/html':ext==='.css'?'text/css':ext==='.js'?'application/javascript':'text/plain'; send(res,200,data,type); });
});
server.listen(PORT,()=>console.log('AMS ERP FINAL PRO running: http://localhost:'+PORT));
